### ISSUE TITLE
US005 - Obter dados de pagamentos

### ISSUE THREAD

**Issue by tallysmartins** [joaaogui/pesquini#10]
**Como** Desenvolvedor
**Eu desejo** obter dados dos pagamentos do governo para as empresas
**Para que** eu possa utilizar estes dados no sistema Pesquini

Responsáveis: 

Task List
- [x] implementar parser dos pagamentos

Critérios de aceitação:

**Comment by aulusdiniz** [comment]
Faltando os responsáveis e os critérios de aceitação
