### ISSUE TITLE
US001 - Visualizar informações sobre legislação de sanções

### ISSUE THREAD

**Issue by tallysmartins** [joaaogui/pesquini#11]
**Como** Usuário
**Eu desejo** visualizar  informações a respeito da legislação de sanções
**Para que** eu possa me informar e compreender melhor o que são e como funcionam as sanções

Responsáveis: @victorhmf @jokman 

Task List
- [x] pesquisar informações sobre a legislação das sanções
- [x] criar página com informações sobre a legislação das sanções

Critérios de aceitação:

-O usuário deve acessar um item de menu escrito "Saiba mais" para acessar a página de informações, referente as legislações de cada tipo de sanção que consta na aplicação. 
-O item de menu referente a página de informações deve estar disponível em todas as páginas do sistema.
-A página de informações deve conter os dados (nome, descrição, lei relacionada).

**Comment by victorhmf** [comment]
Foram pesquisadas as legislações para cada tipo de sanção que consta na aplicação, segue link abaixo:
http://www.portaldatransparencia.gov.br/ceis/SaibaMais.seam
