### ISSUE TITLE
US010 - Refatorar layout dos resultados da busca

### ISSUE THREAD

**Issue by tallysmartins** [joaaogui/pesquini#7]
**Como** Desenvolvedor
**Eu desejo** refatorar o layout dos resultados da pesquisa
**Para** melhorar a interface do usuário

Responsáveis: @AlexandreTK @ruandonato, @leandrokanis

Task List
- [x] adicionar css para melhorar visualização das informações
- [x] escrever testes funcionais (cucumber)

Caso queiram deixar prontos e adiantar os campos abaixo, mesmo estes nao estando prontos:
- [ ] adicionar campo para informação "posição no ranking de sanções"
- [ ] adicionar campo para a informação "posição no ranking de pagamentos" 
- [ ] adicionar campo para a informação "contratada após sanção?"

História técnica sem critérios de aceitação:

**Comment by tallysmartins** [comment]
Melhorar a visualização, principalmente quando há mais de uma sanção. 
Os campos sobre as outras informações podem ser adicionados e posicionados na view mesmo ainda não estando prontos. Seria legal testar com os testes do cucumber se está aparecendo os campos certinho.

**Comment by tallysmartins** [comment]
Fiz a parada lá

**Comment by ruandonato** [comment]
Eu melhorei o layout e fiz a paginação. @AlexandreTK , sinta-se a vontade pra alterar qualquer coisa.

**Comment by ruandonato** [comment]
O teste já estava praticamente feito, só precisava de alguns ajustes. @AlexandreTK
