### ISSUE TITLE
US002 - Adicionar filtro por ano no gráfico de sanções por estado

### ISSUE THREAD

**Issue by tallysmartins** [joaaogui/pesquini#8]
**Como** Usuário
**Eu desejo** visualizar o gráfico de total de sanções por estado em um determinado ano
**Para que** possa comparar em qual estado as empresas mais sofreram sanções no Brasil em um determinado ano

Responsáveis @gustavonascimento  @joaaogui 

Task List
- [x] refatorar cálculo do total de sanções por estado para receber um ano como parâmetro sendo o default o ano atual
- [x] escrever testes unitários

Critérios de aceitação:
- O usuário deve estar ná pagina referente ao gráfico que relaciona as  unidades federativas brasileiras com as sanções aplicadas.
- Nessa página deve existir uma drop down list com os anos nos quais o sistema tem as informações.
- Quando o usuário selecionar o ano, a página deve recarregar e exibir o gráfico atualizado, com os dados do ano selecionado.

**Comment by tallysmartins** [comment]
O método que calcula as sanções deveria estar na model, cada estado deve ter o método que retornar suas sanções, por exemplo

**Comment by leandrokanis** [comment]
vide US008
